# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpctorest.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10grpctorest.proto\x12\ngrpctorest\"?\n\x11GrpcToRestRequest\x12\r\n\x05\x66name\x18\x01 \x01(\t\x12\r\n\x05lname\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\"\"\n\x0fGrpcToRestReply\x12\x0f\n\x07message\x18\x01 \x01(\t2U\n\nGrpcToRest\x12G\n\x07\x43onvert\x12\x1d.grpctorest.GrpcToRestRequest\x1a\x1b.grpctorest.GrpcToRestReply\"\x00\x42;\n io.sean.grpc.examples.grpctorestB\x0fGrpcToRestProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpctorest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n io.sean.grpc.examples.grpctorestB\017GrpcToRestProtoP\001\242\002\003HLW'
  _globals['_GRPCTORESTREQUEST']._serialized_start=32
  _globals['_GRPCTORESTREQUEST']._serialized_end=95
  _globals['_GRPCTORESTREPLY']._serialized_start=97
  _globals['_GRPCTORESTREPLY']._serialized_end=131
  _globals['_GRPCTOREST']._serialized_start=133
  _globals['_GRPCTOREST']._serialized_end=218
# @@protoc_insertion_point(module_scope)
